//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Web.Models
{
    using System;
    
    public enum HotelRoomType : byte
    {
        Restroom = 0,
        Gameroom = 1,
        Workroom = 2,
        Fightroom = 3
    }
}
