//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagotchi
    {
        public int Id { get; set; }
        public Nullable<int> HotelRoomId { get; set; }
        public string Name { get; set; }
        public int Pennies { get; set; }
        public int Level { get; set; }
        public byte Health { get; set; }
        public byte Boredom { get; set; }
        public byte Alive { get; set; }
    
        public virtual HotelRoom HotelRoom { get; set; }
    }
}
